#!/usr/bin/python3

import os
import sys
from typing import *
from argparse import ArgumentParser

import mne
from mne.source_space import SourceSpaces

from common import *

BEM_METHODS = [
	'watershed', 'flash'
]

SOURCE_TYPES = [
	'volume', 'surface'
]

SOURCE_SPACING = [
	'oct4', 'oct6', 'ico4', 'ico6', 'all'
]

def make_argument_parser() -> ArgumentParser:
	parser = ArgumentParser(description='Generate forward solution to use with DSL')
	parser.add_argument('input', metavar='INPUT', help='input file to compute forward solution for')
	parser.add_argument('-q', '--quiet', action='store_true', help='do not show messages')
	parser.add_argument('-s', '--subject', metavar='ID', required=True, help='FreeSurfer subject ID')
	parser.add_argument('-d', '--subjects-dir', metavar='DIR', help='FreeSurfer subjects folder path')
	parser.add_argument('-b', '--bem-method', help='method to use for generating BEM surfaces', **use_first_as_default(BEM_METHODS))
	parser.add_argument('-j', '--source-type', help='type of source space to generate', **use_first_as_default(SOURCE_TYPES))
	parser.add_argument('--source-spacing', help='spacing for source spaces', **use_first_as_default(SOURCE_SPACING))
	parser.add_argument('-t', '--transform', metavar='PATH', type=parse_optional(str), default='fsaverage', help='path to transformation FIF file')
	parser.add_argument('-r', '--regenerate', action='store_true', help='recreate intermediate files')
	parser.add_argument('-z', '--gzip', action='store_true', help='use gzip to compress output data')
	parser.add_argument('-o', '--output', metavar='NAME', required=True, help='used as template for output files')
	return parser

def generate_bem_solution(subject: str, **kwargs) -> mne.bem.ConductorModel:
	surfaces = mne.make_bem_model(subject=subject, **kwargs)
	bem = mne.make_bem_solution(surfaces)
	return bem

def generate_bem_surfaces(subject: str, method: str, **kwargs) -> None:
	if method == 'watershed':
		mne.bem.make_watershed_bem(subject, **kwargs)
	elif method == 'flash':
		mne.bem.make_flash_bem(subject, **kwargs)

def generate_source_space(subject: str, type: str, **kwargs) -> mne.SourceSpaces:
	if type == 'surface':
		return mne.setup_source_space(subject, **kwargs)
	elif type == 'volume':
		return mne.setup_volume_source_space(subject, **kwargs)

def main() -> Optional[int]:
	parser = make_argument_parser()
	if len(sys.argv) == 1:
		parser.print_usage(file=sys.stderr)
		return -1
	
	args = parser.parse_args()
	if args.quiet:
		mne.set_log_level('warning')
	
	subjects_dir = os.getenv('SUBJECTS_DIR')
	if args.subjects_dir:
		mne.set_config('SUBJECTS_DIR', args.subjects_dir)
		subjects_dir = args.subjects_dir
	
	raw = mne.io.read_raw(args.input)
	
	bem = None
	bem_file = make_output_filename(args.output, 'bem', compress=args.gzip)
	if not args.regenerate:
		try:
			bem = mne.read_bem_solution(bem_file)
		except Exception:
			pass
	
	if not bem:
		ws_dir = os.path.join(subjects_dir, args.subject, 'bem', args.bem_method)
		if not os.path.exists(ws_dir) or args.regenerate:
			generate_bem_surfaces(args.subject, args.bem_method, overwrite=True)
		bem = generate_bem_solution(args.subject)
		mne.write_bem_solution(bem_file, bem, overwrite=True)
	
	src_space = None
	src_file = make_output_filename(args.output, 'src', compress=args.gzip)
	if not args.regenerate:
		try:
			src_space = mne.read_source_spaces(src_file)
		except:
			pass
	
	if not src_space:
		if args.source_type == 'surface':
			src_space = generate_source_space(args.subject, 'surface',
			                                  spacing=args.source_spacing)
		if args.source_type == 'volume':
			src_space = generate_source_space(args.subject, 'volume')
		mne.write_source_spaces(src_file, src_space, overwrite=True)
	
	fwd = mne.make_forward_solution(raw.info, args.transform, src_space, bem)
	output_file = make_output_filename(args.output, 'fwd', compress=args.gzip)
	mne.write_forward_solution(output_file, fwd, overwrite=True)


if __name__ == '__main__':
	try:
		res = main()
		sys.exit(res)
	
	except InterruptedError:
		print('Interrupted.', file=sys.stderr)
		sys.exit(-1)
		
	except Exception as e:
		print(f'Error: {e}.', file=sys.stderr)
		sys.exit(-1)
